<h3>Flight Layout</h3>
	<dl>
		<dt>Seats Available</dt>
		<dd>150/200</dd>
	</dl>
	
	<h4>Seat Layout</h4>
	<table class="table table-bordered table-condensed">
		<thead> <!-- Boeing 777 -->
			<tr>
				<th>#</th>
				<th>A</th>
				<th>B</th>
				<th></th>
				<th>C</th>
				<th>D</th>
				<th>E</th>
				<th>F</th>
				<th>G</th>
				<th></th>
				<th>H</th>
				<th>J</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<th>1</th>
				<td>A</td>
				<td>B</td>
				<td></td>
				<td>C</td>
				<td>D</td>
				<td>E</td>
				<td>F</td>
				<td>G</td>
				<td></td>
				<td>H</td>
				<td>J</td>
			</tr>
			<tr>
				<th>2</th>
				<td>A</td>
				<td>B</td>
				<td></td>
				<td>C</td>
				<td>D</td>
				<td>E</td>
				<td>F</td>
				<td>G</td>
				<td></td>
				<td>H</td>
				<td>J</td>
			</tr>
			<tr>
				<th>3</th>
				<td>A</td>
				<td>B</td>
				<td></td>
				<td>C</td>
				<td>D</td>
				<td>E</td>
				<td>F</td>
				<td>G</td>
				<td></td>
				<td>H</td>
				<td>J</td>
			</tr>
			<tr>
				<th>4</th>
				<td>A</td>
				<td>B</td>
				<td></td>
				<td>C</td>
				<td>D</td>
				<td>E</td>
				<td>F</td>
				<td>G</td>
				<td></td>
				<td>H</td>
				<td>J</td>
			</tr>
		</tbody>
	</table>